config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  devise_for :users, :skip => [:registrations]
  scope "/admin" do
    resources :users do
      resources :pets
    end
    get '/doctors', to: 'users#doctors'
    get '/new_doctor' => 'users#new_doctor'
    get '/customers', to: 'users#customers'
    get '/new_customer' => 'users#new_customer'

  end
  resources :appointments
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor, :class_name => 'User'
  belongs_to :customer, :class_name => 'User'

  belongs_to :pet
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_many :appointments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :doctors, ->{ where(role_type: 'Doctor') }
  scope :customers, ->{ where(role_type: 'Customer') }

  has_many :customer_appointments, :class_name => 'Appointment', :foreign_key => 'customer_id'
  has_many :doctor_appointments, :class_name => 'Appointment', :foreign_key => 'doctor_id'

  has_many :pets

private
  def self.all_except(user)
    where.not(id: user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    #devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @pet = @user.pets.new
  end

  def create
    @user = User.find(params[:user_id])
    @pet = @user.pets.new(pet_params)
    if @pet.valid?
      @pet.save
      redirect_to customers_path, notice: 'Pet added'
    else
      render action: :new
    end
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :pet_type, :breed, :salt, :y_age, :m_age, :weight)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    #@users = User.all
    @users = User.all_except(current_user)
  end

  def show
    @user = User.find(params[:id])
    @pets = @user.pets
  end

  def doctors
    @users = User.doctors
  end

  def customers
    @users = User.customers
  end

  def new
    @user = User.new
  end

  def new_doctor
    @user = User.new
  end

  def new_customer
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to root_path, notice: 'User created'
    else
      render action: :new_doctor
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "User updated."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :address, :city, :state, :zip, :school, :years, :role_type, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_active(controller)
    #params[:action] == action && params[:controller] == controller ? "active" : nil
    params[:controller] == controller ? "active" : nil
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/index.html.erb
<h1 class="page-header">
  Appointments
</h1>
<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h4> <%= #link_to "Add User", new_user_path %> </h4>
    </div>
    <div class="panel-body">

      <table id="AppointmentsTable" class="col-md-12 table table-striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Doctor</th>
            <th>Customer</th>
            <th>Pet</th>
          </tr>
        </thead>
        <tbody>
          <% @appointments.each do |appointment| %>
            <tr>
              <td><%= appointment.date %></td>
              <td><%= appointment.doctor.name %></td>
              <td><%= appointment.customer.name %></td>
              <td><%= appointment.pet.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Veterinary</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Veterinary</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Dashboard", root_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
            <i class="glyphicon glyphicon-user"></i> <%= current_user.name %> <span class="caret"></span></a>
            <ul id="g-account-menu" class="dropdown-menu" role="menu">

              <li>
                <%= link_to destroy_user_session_path, method: 'delete' do %>
                  <i class="glyphicon glyphicon-lock" aria-hidden="true"></i> Logout
                <% end%>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>

    </div>
  </div>
</nav>

  <div class="container-fluid">

    <div class="row row-offcanvas row-offcanvas-left">

      <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
        <h3><i class="glyphicon glyphicon-briefcase"></i> Menu</h3>
        <hr>
        <ul class="nav nav-sidebar">
          <li class="<%= menu_active('dashboard') %>"><%= link_to "Dashboard", root_path %></li>

          <li class="<%= menu_active('doctors') %>">
            <%= link_to (doctors_path) do %>
              <i class="glyphicon glyphicon-user" aria-hidden="true"></i> Doctors
            <% end %>
          </li>

          <li class="<%= menu_active('customers') %>">
            <%= link_to (customers_path) do %>
              <i class="glyphicon glyphicon-user" aria-hidden="true"></i> Customers
            <% end %>
          </li>

          </li>
          <li><a href="#"><i class="glyphicon glyphicon-search" aria-hidden="true"></i> Appointments</a></li>
        </ul>

      </div><!--/span-->

      <div class="col-sm-9 col-md-10 main">

        <!--toggle sidebar button-->
        <p class="visible-xs">
          <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
        </p>

        <!-- flash message -->

          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %></p>
          <% end %>

          <%= yield %>

      </div>
    </div>
  </div><!--/.container-->

  <footer>
    <p class="pull-right">©2015</p>
  </footer>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liquidaciones</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<!--login modal-->
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">

        <%= yield %>

      </div>
      <div class="modal-footer">
        <div class="col-md-12">
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %></p>
          <% end %>
       </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/pets/new.html.erb
<div class="col-md-12">
  <div class="col-md-6 col-md-3 panel panel-default">
    <div class="panel-body">
      <h2>Add Pet</h2>
      <div class="form-inputs">
        <%= simple_form_for [@user, @pet] do |f| %>
          <%= f.error_notification %>
          <%= f.input :name, required: true, autofocus: true %>
          <%= f.input :pet_type %>
          <%= f.input :breed %>
          <%= f.input :y_age, label: 'Years: ' %>
          <%= f.input :m_age, label: 'Months: ' %>
          <%= f.input :weight %>
          <div class="form-actions">
            <%= f.button :submit, class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/customers.html.erb
<h1 class="page-header">
  Customers
</h1>
<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h4> <%= link_to "Add Customer", new_customer_path %> </h4>
    </div>
    <div class="panel-body">

      <table id="UsersTable" class="col-md-12 table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>email</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.name, user_path(user) %></td>
              <td><%= user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/doctors.html.erb
<h1 class="page-header">
  Doctors
</h1>
<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h4> <%= link_to "Add Doctor", new_doctor_path %> </h4>
    </div>
    <div class="panel-body">

      <table id="UsersTable" class="col-md-12 table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>email</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.name, edit_user_path(user) %></td>
              <td><%= user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        <i class="glyphicon glyphicon-wrench pull-right"></i>
        <h4>Edit <%= @user.role_type.to_s + @user.name.to_s %></h4>
      </div>
    </div><!--head-->
    <div class="panel-body">
      <div class="form-inputs">
        <div class="col-md-6">
          <%= simple_form_for @user do |f| %>
            <%= f.error_notification %>
            <%= f.input :name, required: true, autofocus: true %>
            <%= f.input :email, required: true %>
            <%= f.input :address %>
            <%= f.input :city %>
            <%= f.input :state %>
            <%= f.input :zip %>
            <% if @user.role_type == 'Doctor' %>
              <%= f.input :school %>
              <%= f.input :years %>
            <% end %>
        </div><!--col 6-->

        <div class="form-actions col-md-10">
          <%= f.button :submit, class: 'btn btn-primary btn-lg pull-right' %>
        </div>
          <% end %>
      </div>
    </div><!--body-->
  </div><!--content-->
</div><!--col 12-->

app/views/users/index.html.erb
<h1 class="page-header">
  Users
</h1>
<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h4> <%= link_to "Add User", new_user_path %> </h4>
    </div>
    <div class="panel-body">

      <table id="UsersTable" class="col-md-12 table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>email</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-md-12">
  <div class="col-md-6 col-md-3 panel panel-default">
    <div class="panel-body">
      <h2>Add User</h2>
      <div class="form-inputs">
        <%= simple_form_for @user do |f| %>
          <%= f.error_notification %>
          <%= f.input :name, required: true, autofocus: true %>
          <%= f.input :email, required: true %>
          <%= f.input :password,  required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
          <div class="form-actions">
            <%= f.button :submit, class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new_customer.html.erb
<div class="col-md-12">
  <div class="col-md-6 col-md-3 panel panel-default">
    <div class="panel-body">
      <h2>Add Customer</h2>
      <div class="form-inputs">
        <%= simple_form_for @user do |f| %>
          <%= f.error_notification %>
          <%= f.input :name, required: true, autofocus: true %>
          <%= f.input :email, required: true %>
          <%= f.input :address %>
          <%= f.input :city %>
          <%= f.input :state %>
          <%= f.input :zip %>
          <%= f.input :role_type, :as => :hidden, :input_html => { :value => 'Customer' } %>
          <%= f.input :password,  required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
          <div class="form-actions">
            <%= f.button :submit, 'Add Customer', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new_doctor.html.erb
<div class="col-md-12">
  <div class="col-md-6 col-md-3 panel panel-default">
    <div class="panel-body">
      <h2>Add Doctor</h2>
      <div class="form-inputs">
        <%= simple_form_for @user do |f| %>
          <%= f.error_notification %>
          <%= f.input :name, required: true, autofocus: true %>
          <%= f.input :email, required: true %>
          <%= f.input :address %>
          <%= f.input :city %>
          <%= f.input :state %>
          <%= f.input :zip %>
          <%= f.input :school %>
          <%= f.input :years %>
          <%= f.input :role_type, :as => :hidden, :input_html => { :value => 'Doctor' } %>
          <%= f.input :password,  required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
          <div class="form-actions">
            <%= f.button :submit, 'Add Doctor', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="page-header">
  <h1> <%= @user.name %></h1>
  <p> <%= @user.email %></p>
</h1>
<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h4> <%= link_to "Add Pet", new_user_pet_path(@user) %> </h4>
    </div>
    <div class="panel-body">

      <table id="PetsTable" class="col-md-12 table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Breed</th>
          </tr>
        </thead>
        <tbody>
          <% @pets.each do |pet| %>
            <tr>
              <td><%= pet.name %></td>
              <td><%= pet.pet_type %></td>
              <td><%= pet.breed %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>